# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - bash: |
      npm install
    displayName: 'npm install'

  - bash: |
      npx playwright install chromium
    displayName: 'npm install'

  - bash: |
      npm run pw:examples:vrt:ci
    displayName: 'run Playwright VRT tests'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/examples-vrt-playwright/test-results/'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Examples-VRT-Artifacts'
      OverWrite: true
    condition: always()
    displayName: 'copy vrt artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Examples-VRT-Artifacts/'
      ArtifactName: 'Examples-VRT-Artifacts'
      publishLocation: 'Container'
    condition: always()
    displayName: 'publish vrt artifacts'