# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: "windows-latest"

jobs:
- job: Playwright

  strategy:
    matrix:
      Shard_1: { SHARD_INDEX: 1, SHARD_TOTAL: 3 }
      Shard_2: { SHARD_INDEX: 2, SHARD_TOTAL: 3 }
      Shard_3: { SHARD_INDEX: 3, SHARD_TOTAL: 3 }

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '24.x'
    displayName: 'Install Node.js'

  - bash: |
      npm install
    displayName: 'npm install'

  - bash: |
      npm run examples:ci -- --shard=$(SHARD_INDEX)/$(SHARD_TOTAL)
    displayName: 'run Playwright tests'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/test-results/'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Site-Test-Artifacts'
      OverWrite: true
    condition: failed()
    displayName: 'copy vrt artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Site-Test-Artifacts/'
      ArtifactName: 'Site-Test-Artifacts'
      publishLocation: 'Container'
    condition: failed()
    displayName: 'publish test artifacts'